# Generated by Django 2.0.6 on 2018-07-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_photo', '0003_auto_20180719_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='photo_batch',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='testing/tests'),
        ),
    ]
