# Generated by Django 2.0.6 on 2018-07-20 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_photo', '0004_auto_20180720_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'managed': False},
        ),
    ]
