# Generated by Django 2.0.6 on 2018-07-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_photo', '0005_auto_20180720_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photobatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photobatch_id', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
            options={
                'db_table': 'excavation"."photobatch_processing',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='attachment',
            table='excavation"."photobatch_photos',
        ),
    ]
