# Generated by Django 2.0.2 on 2018-06-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(default='', max_length=200)),
                ('address_1', models.CharField(default='', max_length=200)),
                ('address_2', models.CharField(default='', max_length=200)),
                ('region', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('zip', models.CharField(default='', max_length=200)),
                ('country', models.CharField(default='Turkey', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'stores',
                'db_table': 'samples"."store',
                'managed': False,
            },
        ),
    ]
