# Generated by Django 2.0.6 on 2018-06-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('Samples_id', models.AutoField(primary_key=True, serialize=False)),
                ('Samples_identifier', models.IntegerField(blank=True, null=True)),
                ('Samples_type', models.CharField(blank=True, max_length=100, null=True)),
                ('current_Samples_tmp', models.CharField(blank=True, max_length=100, null=True)),
                ('Samples_name', models.CharField(blank=True, max_length=100, null=True)),
                ('orderby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sampless',
                'db_table': 'samples"."Samples',
                'ordering': ['orderby'],
                'managed': False,
            },
        ),
    ]
