# Generated by Django 2.0.6 on 2018-06-29 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_pagefilter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samples',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='samples',
            table='samples"."samples',
        ),
    ]
