# Generated by Django 2.0.6 on 2018-07-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Botany',
            fields=[
                ('botany_id', models.AutoField(primary_key=True, serialize=False)),
                ('sample_id', models.IntegerField(blank=True, null=True)),
                ('area_easting', models.IntegerField(blank=True, null=True)),
                ('area_northing', models.IntegerField(blank=True, null=True)),
                ('context_number', models.IntegerField(blank=True, null=True)),
                ('sample_number', models.IntegerField(blank=True, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('analyst', models.CharField(default='', max_length=200)),
                ('notes', models.CharField(default='', max_length=600)),
            ],
            options={
                'db_table': 'samples"."botany',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BotanyFraction',
            fields=[
                ('fraction_id', models.AutoField(primary_key=True, serialize=False)),
                ('proportion_analysed', models.DecimalField(decimal_places=3, max_digits=5)),
                ('soil_volume', models.DecimalField(decimal_places=4, max_digits=15)),
                ('sample_volume', models.DecimalField(decimal_places=4, max_digits=15)),
                ('sample_weight', models.DecimalField(decimal_places=4, max_digits=15)),
            ],
            options={
                'db_table': 'samples"."botany_fraction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FractionComposition',
            fields=[
                ('fract_comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_type', models.CharField(default='', max_length=50)),
                ('fraction', models.CharField(default='', max_length=50)),
                ('type_count', models.DecimalField(decimal_places=4, max_digits=15)),
                ('whole_weight', models.DecimalField(decimal_places=4, max_digits=15)),
                ('fragment_weight', models.DecimalField(decimal_places=4, max_digits=15)),
            ],
            options={
                'db_table': 'samples"."fraction_composition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FractionMaterialsPresent',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('material', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'samples"."materials_present',
                'managed': False,
            },
        ),
    ]
