# Generated by Django 2.0.6 on 2018-07-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fraction',
            fields=[
                ('fraction_id', models.AutoField(primary_key=True, serialize=False)),
                ('proportion_analysed', models.DecimalField(decimal_places=3, max_digits=5)),
                ('soil_volume', models.DecimalField(decimal_places=4, max_digits=15)),
                ('sample_volume', models.DecimalField(decimal_places=4, max_digits=15)),
                ('sample_weight', models.DecimalField(decimal_places=4, max_digits=15)),
            ],
            options={
                'db_table': 'samples"."fraction',
                'managed': False,
            },
        ),
    ]
