# Generated by Django 2.0.6 on 2018-07-12 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botany', '0002_fraction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botany',
            options={'managed': False, 'verbose_name_plural': 'botany'},
        ),
    ]
