# Generated by Django 2.0.6 on 2018-07-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooarch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zooarch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_easting', models.IntegerField()),
                ('area_northing', models.IntegerField()),
                ('context_number', models.IntegerField()),
                ('sample_number', models.IntegerField()),
                ('element', models.CharField(choices=[(1, 2)], default='', max_length=100)),
                ('portion', models.CharField(choices=[(1, 2)], default='', max_length=100)),
                ('side', models.CharField(choices=[(1, 2)], default='', max_length=25)),
                ('sex', models.CharField(choices=[(1, 2)], default='', max_length=25)),
                ('taxonomic_description', models.CharField(choices=[(1, 2)], default='', max_length=100)),
                ('fusion', models.CharField(choices=[(1, 2)], default='', max_length=50)),
                ('age_estimation', models.CharField(blank=True, choices=[(1, 2)], default='', max_length=50, null=True)),
                ('tooth_wear', models.CharField(blank=True, choices=[(1, 2)], default='', max_length=25, null=True)),
                ('status', models.CharField(blank=True, choices=[(1, 2)], default='', max_length=30, null=True)),
            ],
            options={
                'db_table': 'samples"."faunal_samples',
                'managed': False,
            },
        ),
    ]
