# Generated by Django 2.0.6 on 2018-07-02 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zooarch', '0002_zooarch'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='zooarch',
            table='samples"."samples',
        ),
    ]
