# Generated by Django 2.0.6 on 2018-07-02 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zooarch', '0003_auto_20180702_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qnisp',
            options={'managed': False, 'ordering': ['-qnisp_id']},
        ),
    ]
