# Generated by Django 2.0.6 on 2018-07-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zooarch', '0004_auto_20180702_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zooarchsamples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_easting', models.IntegerField()),
                ('area_northing', models.IntegerField()),
                ('context_number', models.IntegerField()),
                ('sample_number', models.IntegerField()),
                ('element', models.CharField(blank=True, max_length=100, null=True)),
                ('portion', models.CharField(blank=True, max_length=100, null=True)),
                ('side', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(blank=True, max_length=100, null=True)),
                ('taxonomic_description', models.CharField(blank=True, max_length=100, null=True)),
                ('fusion', models.CharField(blank=True, max_length=50, null=True)),
                ('age_estimation', models.CharField(blank=True, max_length=50, null=True)),
                ('tooth_wear', models.CharField(blank=True, max_length=25, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'samples"."samples',
                'managed': False,
            },
        ),
    ]
