# Generated by Django 2.0.6 on 2018-07-09 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zooarch', '0005_zooarchsamples'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='zooarchsamples',
            table='samples"."faunal_samples',
        ),
    ]
