# Generated by Django 2.0.6 on 2018-06-23 05:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trench_99_528',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('contextkey', models.CharField(max_length=20, primary_key=True)),
                ('type', models.CharField(max_length=50)),
                ('shape_leng', models.IntegerField()),
                ('shape_area', models.IntegerField()),
                ('phase', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Trench 99 526',
                'db_table': 'excavation"."gis_99_526_polygon',
                'managed': False,
            },
        ),
    ]
