# Generated by Django 2.0.6 on 2018-07-16 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joinsamplecontainer',
            options={'managed': False, 'ordering': ['container_id', 'id']},
        ),
    ]
