# Generated by Django 2.0.6 on 2018-06-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processing3d',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photobatch_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('prefix', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('area_easting', models.IntegerField()),
                ('area_northing', models.IntegerField()),
                ('context_number', models.IntegerField()),
                ('number_of_photos', models.IntegerField(blank=True, null=True)),
                ('number_targets', models.IntegerField(blank=True, null=True)),
                ('processed_on', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('processed_by', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('camera_model', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('imported_photoscan', models.NullBooleanField()),
                ('aligned', models.NullBooleanField()),
                ('align_accuracy', models.CharField(default='medium', max_length=200)),
                ('align_pair_selection', models.CharField(default='disabled', max_length=200)),
                ('align_keypoint_limit', models.IntegerField(default=40000)),
                ('align_tiepoint_limit', models.IntegerField(default=4000)),
                ('detected_targets', models.NullBooleanField()),
                ('target_type', models.CharField(default='circular 12 bit', max_length=200)),
                ('target_tolerance', models.IntegerField(default=50)),
                ('target_origional_error', models.IntegerField(blank=True, null=True)),
                ('target_optimised_error', models.IntegerField(blank=True, null=True)),
                ('dense_pointcloud', models.NullBooleanField()),
                ('mesh', models.NullBooleanField()),
                ('mesh_type', models.CharField(default='arbitrary', max_length=200)),
                ('mesh_face_count', models.CharField(default='medium', max_length=200)),
                ('mesh_interpolation', models.CharField(default='disabled', max_length=200)),
                ('texture', models.NullBooleanField()),
                ('texture_defaults', models.IntegerField(blank=True, null=True)),
                ('dem', models.NullBooleanField()),
                ('dem_coordinate_system', models.IntegerField(default=32635)),
                ('dem_source_data', models.CharField(default='dense cloud', max_length=200)),
                ('dem_interpolation', models.CharField(default='disabled', max_length=200)),
                ('orthomosaic', models.NullBooleanField()),
                ('orthomosaic_type', models.CharField(default='geographic', max_length=200)),
                ('orthomosaic_pixel_size', models.IntegerField(blank=True, null=True)),
                ('export_points', models.NullBooleanField()),
                ('export_points_filename', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('export_points_offsets', models.CharField(default='X=580000 Y=4275000 Z=0', max_length=200)),
                ('export_report_pdf', models.NullBooleanField()),
                ('export_orthophoto', models.NullBooleanField()),
                ('export_dem', models.NullBooleanField()),
                ('export_dem_pixel_size', models.IntegerField(blank=True, null=True)),
                ('export_dem_geodatabase', models.NullBooleanField()),
                ('folder_processed', models.NullBooleanField()),
                ('processing_notes', models.TextField()),
            ],
            options={
                'db_table': 'excavation"."photobatch_processing',
                'managed': False,
            },
        ),
    ]
