# Generated by Django 2.0.6 on 2018-06-27 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial3d', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processing3d',
            options={'managed': False, 'ordering': ['-folder_processed', 'photobatch_id']},
        ),
    ]
