# Generated by Django 2.0.6 on 2018-07-02 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial3d', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photobatch',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='photobatch',
            table='samples"."samples',
        ),
    ]
