# Generated by Django 2.0.6 on 2018-07-03 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial3d', '0003_auto_20180702_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photobatch',
            options={'managed': False},
        ),
    ]
