# Generated by Django 2.0.6 on 2018-07-03 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spatial3d', '0004_auto_20180703_0703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photobatch',
            options={'managed': False, 'ordering': ['-folder_processed', 'created_timestamp']},
        ),
    ]
